#!/bin/sh

START=""

if [[ $# -ge 1 ]]; then
	START="--start-at-task=\"$*\""
fi

export ANSIBLE_HOST_KEY_CHECKING=False
ansible-playbook --inventory=.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory -v --step ${START} site.yml
