#!/bin/bash

SCRIPT_DIR=$(realpath $(dirname $0))

if [[ "x$1" == "xget" ]]; then
	if [[ "x$2" != "xnamespaces" ]]; then
		echo "USAGE"
		exit 1
	fi

	NAMESPACE="$3"

	if [[ "$NAMESPACE" == "invalid" ]]; then
		exit 1
	fi
elif [[ "x$1" == "xconfig" ]]; then
	echo "aplo"
fi

exit 0
