#!/bin/bash
# Copyright (c) 2018 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
TOPOLOGY='topology-minikube.json'
CLI='kubectl'

set -ex

minikube ssh "\
	sudo truncate -s 10G /mnt/vda1/heketi-bricks.img \
	&& sudo losetup /dev/loop1 /mnt/vda1/heketi-bricks.img \
	&& sudo pvcreate /dev/loop1 \
"

${SCRIPT_DIR}/gk-deploy --yes --single-node --cli ${CLI} --deploy-gluster ${SCRIPT_DIR}/${TOPOLOGY}

HEKETI_URL=$(${CLI} get --no-headers endpoints/heketi | awk '{print $2}')

if minikube addons list | grep -q "default-storageclass: enabled" ; then
  minikube addons disable default-storageclass
  ${CLI} patch storageclass standard -p '{"metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"false"}}}'
fi

${CLI} create -f - <<EOF
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterfs-storage
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://${HEKETI_URL}"
  volumetype: "none"
EOF
